export const cipherAgentPayAbi = [
  {
    type: "function",
    name: "createAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agent", type: "address" },
      { name: "initialMerchant", type: "address" },
      { name: "initialBudget", type: "bytes32" },
      { name: "perPaymentLimit", type: "bytes32" },
      { name: "totalSpendLimit", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rotatePolicy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agent", type: "address" },
      { name: "newBudget", type: "bytes32" },
      { name: "newPerPaymentLimit", type: "bytes32" },
      { name: "newTotalSpendLimit", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "fundAgent",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "pausePolicy",
    stateMutability: "nonpayable",
    inputs: [{ name: "paused", type: "bool" }],
    outputs: [],
  },
  {
    type: "function",
    name: "requestPayment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "merchant", type: "address" },
      { name: "amount", type: "bytes32" },
      { name: "inputProof", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getAgent",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [
      { name: "agent", type: "address" },
      { name: "auditor", type: "address" },
      { name: "initialized", type: "bool" },
      { name: "paused", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "allowedMerchant",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "merchant", type: "address" },
    ],
    outputs: [{ name: "allowed", type: "bool" }],
  },
  {
    type: "function",
    name: "paymentNonce",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "setMerchant",
    stateMutability: "nonpayable",
    inputs: [
      { name: "merchant", type: "address" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setAuditor",
    stateMutability: "nonpayable",
    inputs: [{ name: "auditor", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "encryptedBalance",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedPerPaymentLimit",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedTotalSpendLimit",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedTotalSpent",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedLastPaymentAmount",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedLastPaymentApproved",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "encryptedMerchantRevenue",
    stateMutability: "view",
    inputs: [{ name: "merchant", type: "address" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "event",
    name: "PolicyCreated",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "initialMerchant", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PolicyRotated",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "agent", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PolicyPaused",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "paused", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PaymentEvaluated",
    inputs: [
      { name: "owner", type: "address", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "paymentId", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
